### ISSUE TITLE
Error: Pandas not defined

### ISSUE THREAD

**Issue by atte-wsp** [HSLdevcom/helmet-model-system#273] opened 2021-03-16 17:22 UTC
Somehow this did not come up earlier when testing #244. Last iteration of EmmeAssignment returns error `NameError: global name 'pandas' is not defined`. 

https://github.com/HSLdevcom/helmet-model-system/blob/b0010fe75f86c50348d982e3d39bac494ae3a188/Scripts/assignment/emme_assignment.py#L182

**Comment by zptro** [comment] 2021-03-17 07:22
Duplicate of #270

**Closed by zptro** 2021-03-17 07:22 UTC
Labels: duplicate
