### ISSUE TITLE
.omx matrices should be in gitignore

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-model-system#493] opened 2023-03-13 11:04 UTC
I suggest the .omx matrices for testing should be excluded in .gitignore after the first run so that they do not appear in commit options unnecessarily. Any other opinions?

**Comment by johpiip** [comment] 2023-05-23 11:14
Duplicate of #414

**Closed by johpiip** 2023-05-23 11:14 UTC
